# Here's a step-by-step guide to building and training a simple Sequential model using Keras for classifying the Iris dataset:

* Import necessary libraries
* Load and preprocess the data
* Build the model
* Compile and train the model
* Evaluate the model

In [1]:
# Import necessary libraries
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Input, Activation

In [2]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

In [3]:
print(len(X))
print(X[0])

150
[5.1 3.5 1.4 0.2]


In [4]:
print(len(y))
print(y[0])

150
[0]


In [5]:
# One-hot encode the target variable
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y)

In [6]:
print(len(y))
print(y[0])

150
[1. 0. 0.]


In [7]:
# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [8]:
print(len(X))
print(X[0])

150
[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]


In [9]:
# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Build the model
model = Sequential()

# Use Input layer to specify the shape
model.add(Input(shape=(X_train.shape[1],)))

# Add SimpleRNN layers
model.add(Dense(units=64))
model.add(Activation('relu'))
model.add(Dense(units=64))
model.add(Activation('relu'))
model.add(Dense(units=y_train.shape[1]))
model.add(Activation('softmax'))

In [11]:
# Summary of the model
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation (Activation)              │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           4,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_1 (Activation)            │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 3)                   │             195 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_2 (Activation)            │ (None, 3)                   │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,675 (18.26 KB)

 Trainable params: 4,675 (18.26 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=5, verbose=2)

Epoch 1/50
24/24 - 1s - 38ms/step - accuracy: 0.5500 - loss: 0.9502
Epoch 2/50
24/24 - 0s - 2ms/step - accuracy: 0.7500 - loss: 0.6178
Epoch 3/50
24/24 - 0s - 3ms/step - accuracy: 0.8250 - loss: 0.4498
Epoch 4/50
24/24 - 0s - 3ms/step - accuracy: 0.8417 - loss: 0.3630
Epoch 5/50
24/24 - 0s - 3ms/step - accuracy: 0.8500 - loss: 0.3192
Epoch 6/50
24/24 - 0s - 2ms/step - accuracy: 0.8833 - loss: 0.2814
Epoch 7/50
24/24 - 0s - 2ms/step - accuracy: 0.8667 - loss: 0.2549
Epoch 8/50
24/24 - 0s - 2ms/step - accuracy: 0.9250 - loss: 0.2316
Epoch 9/50
24/24 - 0s - 3ms/step - accuracy: 0.9417 - loss: 0.2053
Epoch 10/50
24/24 - 0s - 3ms/step - accuracy: 0.9500 - loss: 0.1833
Epoch 11/50
24/24 - 0s - 2ms/step - accuracy: 0.9583 - loss: 0.1665
Epoch 12/50
24/24 - 0s - 3ms/step - accuracy: 0.9500 - loss: 0.1493
Epoch 13/50
24/24 - 0s - 3ms/step - accuracy: 0.9583 - loss: 0.1352
Epoch 14/50
24/24 - 0s - 3ms/step - accuracy: 0.9583 - loss: 0.1232
Epoch 15/50
24/24 - 0s - 3ms/step - accuracy: 0.9667 - l

In [14]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test loss: {loss:.4f}')
print(f'Test accuracy: {accuracy:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - accuracy: 1.0000 - loss: 0.0227
Test loss: 0.0227
Test accuracy: 1.0000


In [15]:
# Predict on new data
new_data = np.array([[5.1, 3.5, 1.4, 0.2]]) # Example data points

# Standardize the new data using the same scaler fitted on the training data
new_data = scaler.transform(new_data)

# Make predictions
predictions = model.predict(new_data)

# Convert predictions from one-hot encoded format back to class labels
predicted_classes = encoder.inverse_transform(predictions)

print(f'Predictions (one-hot encoded):\n{predictions}')
print(f'Predicted class labels:\n{predicted_classes}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
Predictions (one-hot encoded):
[[9.9992871e-01 7.1246293e-05 1.8013386e-09]]
Predicted class labels:
[[0]]


## Repeating the same building and evaluation processes but with trying layers such as Conv1D, Conv2D, Flatten, MaxPooling1D

In [16]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Flatten, Dense, Activation, MaxPooling1D

In [17]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

In [18]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [19]:
print(y)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]


In [20]:
# One-hot encode the target variable
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y)

In [21]:
# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [22]:
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [23]:
# Reshape the data for CNN input (samples, time steps, features)
X = X.reshape(X.shape[0], X.shape[1], 1)

In [24]:
X

array([[[-9.00681170e-01],
        [ 1.01900435e+00],
        [-1.34022653e+00],
        [-1.31544430e+00]],

       [[-1.14301691e+00],
        [-1.31979479e-01],
        [-1.34022653e+00],
        [-1.31544430e+00]],

       [[-1.38535265e+00],
        [ 3.28414053e-01],
        [-1.39706395e+00],
        [-1.31544430e+00]],

       [[-1.50652052e+00],
        [ 9.82172869e-02],
        [-1.28338910e+00],
        [-1.31544430e+00]],

       [[-1.02184904e+00],
        [ 1.24920112e+00],
        [-1.34022653e+00],
        [-1.31544430e+00]],

       [[-5.37177559e-01],
        [ 1.93979142e+00],
        [-1.16971425e+00],
        [-1.05217993e+00]],

       [[-1.50652052e+00],
        [ 7.88807586e-01],
        [-1.34022653e+00],
        [-1.18381211e+00]],

       [[-1.02184904e+00],
        [ 7.88807586e-01],
        [-1.28338910e+00],
        [-1.31544430e+00]],

       [[-1.74885626e+00],
        [-3.62176246e-01],
        [-1.34022653e+00],
        [-1.31544430e+00]],

       [[-

In [25]:
# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
# Build the CNN model
model = Sequential()

# Use Input layer to specify the shape
model.add(Input(shape=(X_train.shape[1], 1)))

# Add SimpleRNN layers
model.add(Conv1D(filters=32, kernel_size=2, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=y_train.shape[1], activation='softmax'))

In [27]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [28]:
# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=5, verbose=2)

Epoch 1/50
24/24 - 1s - 41ms/step - accuracy: 0.4250 - loss: 1.0993
Epoch 2/50
24/24 - 0s - 3ms/step - accuracy: 0.5333 - loss: 1.0236
Epoch 3/50
24/24 - 0s - 3ms/step - accuracy: 0.6417 - loss: 0.9741
Epoch 4/50
24/24 - 0s - 3ms/step - accuracy: 0.6333 - loss: 0.9331
Epoch 5/50
24/24 - 0s - 3ms/step - accuracy: 0.6417 - loss: 0.8964
Epoch 6/50
24/24 - 0s - 3ms/step - accuracy: 0.6750 - loss: 0.8564
Epoch 7/50
24/24 - 0s - 3ms/step - accuracy: 0.6833 - loss: 0.8210
Epoch 8/50
24/24 - 0s - 3ms/step - accuracy: 0.6833 - loss: 0.7870
Epoch 9/50
24/24 - 0s - 3ms/step - accuracy: 0.6667 - loss: 0.7495
Epoch 10/50
24/24 - 0s - 3ms/step - accuracy: 0.7167 - loss: 0.7154
Epoch 11/50
24/24 - 0s - 3ms/step - accuracy: 0.7083 - loss: 0.6926
Epoch 12/50
24/24 - 0s - 3ms/step - accuracy: 0.7417 - loss: 0.6610
Epoch 13/50
24/24 - 0s - 3ms/step - accuracy: 0.7667 - loss: 0.6428
Epoch 14/50
24/24 - 0s - 4ms/step - accuracy: 0.7750 - loss: 0.6148
Epoch 15/50
24/24 - 0s - 4ms/step - accuracy: 0.7917 - l

In [29]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test loss: {loss:.4f}')
print(f'Test accuracy: {accuracy:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 272ms/step - accuracy: 0.8333 - loss: 0.4727
Test loss: 0.4727
Test accuracy: 0.8333


In [30]:
# Predict on new data
new_data = X_test[:5]  # Using the first 5 test samples as example
predictions = model.predict(new_data)

# Convert predictions from one-hot encoded format back to class labels
predicted_classes = np.argmax(predictions, axis=1)
true_classes = np.argmax(y_test[:5], axis=1)

print(f'Predicted class labels: {predicted_classes}')
print(f'True class labels: {true_classes}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
Predicted class labels: [1 0 0 1 1]
True class labels: [1 0 2 1 1]


In [31]:
input_shape=(X_train.shape[1], 1)

In [32]:
input_shape

(4, 1)